<?php

use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_locale_translation_projects_alter().
 */
function premium_calendar_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('premium_calendar')->getPath();
  $projects['premium_calendar']['info']['interface translation server pattern'] = $path.'/translations/%language.po';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function premium_calendar_preprocess_block__inline_block__calendar(array &$variables) {
  /** @var \Drupal\block_content\Entity\BlockContent $block */
  $block = $variables['content']['#block_content'];

  /** @var \Drupal\premium_calendar\CalendarService $calendarService */
  $calendarService = \Drupal::service('premium_calendar');
  $settings = $calendarService->getCalendarOptions($block);

  $attached['library'][] = 'premium_calendar/premium_calendar';

  if (!empty($settings['options']['themeSystem']) && ($settings['options']['themeSystem'] !== 'standard')) {
    $attached['library'][] = 'fullcalendar/fullcalendar.' . $settings['options']['themeSystem'];
  }

  if (!empty($settings['locale']) && $settings['locale'] !== 'en') {
    $attached['library'][] = 'fullcalendar/fullcalendar.locales';
  }

  $attached['drupalSettings']['premium_calendar'] = [
    'js-premium-calendar-' . $block->id() => $settings,
  ];

  $variables['#attached'] = $attached;
  $variables['content']['calendar'] = [
    '#type' => 'container',
    '#attributes' => [
      'id' => 'js-premium-calendar-' . $block->id(),
      'class' => ['premium_calendar--wrapper']
    ]
  ];
}

/**
 * Implements hook_transform_alter().
 */
function premium_calendar_entity_transform_alter(&$transformation) {
  /** @var ContentEntityInterface $entity */
  $entity = $transformation['#entity'];

  /* Layout block alterations */
  if ($transformation['entity_type'] === 'block_content') {
    /** @var \Drupal\block_content\Entity\BlockContent $block */
    $block = $entity;

    if ($transformation['bundle'] == 'calendar') {
      /** @var \Drupal\premium_calendar\CalendarService $calendarService */
      $calendarService = \Drupal::service('premium_calendar');
      $settings = $calendarService->getCalendarOptions($block);

      $transformation['settings'] = $settings;
    }
  }
}
